(chore) Update Contributing section
hoverinc/ray-tracing-renderer pull request #166
Opened 2020-09-08 01:18 UTC by elfrank

## Brief Description
Please include a **summary** of the change and/or which issue is fixed. Please also include *relevant motivation and context*.

## Image(s) or GIFs (if applicable)
Update "Contributing" section on the README and wiki page.

Specify we are looking to improve test coverage and Code Climate score.

## Pull Request Guidelines

- [ ] I have added pull requests labels which describe my contribution.
- [ ] All existing tests passed.
    - [ ] I have added tests to cover my changes, of which pass.
- [ ] I have [compared](https://github.com/hoverinc/ray-tracing-renderer/wiki/Contributing#comparing-changes) the render output of my branch to `master`.
- [ ] My code has passed the ESLint configuration for this project.
- [ ] My change requires modifications to the documentation.
    - [ ] I have updated the documentation accordingly.

2020-09-10 01:30 UTC, lyonsno requested changes
This is a good contribution to the repo for supporting open-source, everything looks great except the issue with the contributing page.

2020-09-10 01:30 UTC, lyonsno commented on README.md
> +This repository started as a side-project and the time we invest on it is limited. It make take us a few days to get back to you but please bring your ideas forward. We'll do our best to respond prom
`nit` It make take us a few days => it may take us a few days

Good call adding that disclaimer

2020-09-10 01:30 UTC, lyonsno commented on README.md
> +[Demo](https://hoverinc.github.io/ray-tracing-renderer/scenes/sample-models/) | [User Guide](https://github.com/hoverinc/ray-tracing-renderer/wiki/User-Guide) | [API Reference](https://github.com/hov
The contributing link seems to be broken? When I click on it it just brings me to the main repo page.

Clicking the `contributing` link on the repo page takes me to a page asking me if I want to create a `contributing` section.

2020-09-14 04:02 UTC, elfrank commented on README.md
> +This repository started as a side-project and the time we invest on it is limited. It make take us a few days to get back to you but please bring your ideas forward. We'll do our best to respond prom
good catch, fixed the typo

2020-09-14 04:08 UTC, elfrank commented on README.md
> +[Demo](https://hoverinc.github.io/ray-tracing-renderer/scenes/sample-models/) | [User Guide](https://github.com/hoverinc/ray-tracing-renderer/wiki/User-Guide) | [API Reference](https://github.com/hov
The link https://github.com/hoverinc/ray-tracing-renderer#contributing doesn't exist in master yet. Once the PR gets merged, the link should work. The same way the following page works: https://github.com/hoverinc/ray-tracing-renderer/#introduction

2020-09-25 19:06 UTC, lyonsno approved these changes
Ok, LGTM then!

2020-10-04 23:15 UTC, merged